services:
  - type: web
    name: book-club-be
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    preDeployCommand: alembic upgrade head
    healthCheckPath: /health
    envVars: []
    
previews:
  generation: off
